### ISSUE TITLE
cast project tip：project ':bonsoir' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.30

### ISSUE THREAD

**Issue by banchengcunluo** [johnvuko/flutter_cast#38]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':bonsoir' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.30

**Comment by mansillacr** [comment]
I have a same problem, any solution for this problem

**Comment by jonathantribouharet** [comment]
I have released a new version with bonsoir v3.0.0.

**Comment by johnvuko** [comment]
Hello,
I've release a new version 2.1.0 without the upper limit for bonsoir, which should solve the issue.
