### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by Feichtmeier** [johnvuko/flutter_cast#40]
hi 👋 

is linux support planned in the future?
would love to use it in https://github.com/ubuntu-flutter-community/musicpod/issues/91
best regards

**Comment by guyluz11** [comment]
I have created a fork with Linux support (tested it), branch name is `combined-master`.

https://github.com/guyluz11/flutter_cast/tree/combined-master

You can add it in `pubspec.yaml` like this

```dart
cast: 
  git: 
    url: "https://github.com/guyluz11/flutter_cast.git"
    ref: "combined-master"
```

**Comment by Feichtmeier** [comment]
Thank you @guyluz11 !!!
I will try it soon and report back

**Comment by guyluz11** [comment]
You can also try `multicast_version` branch which is full of goodies that I've created and easy to access functions

**Comment by johnvuko** [comment]
Hello,
I've release a new version 2.1.0 without the upper limit for bonsoir, which should solve the issue.

**Comment by Feichtmeier** [comment]
> Hello, I've release a new version 2.1.0 without the upper limit for bonsoir, which should solve the issue.

Cool! Thank you for your work! WIll try
